// <auto-generated />
using System;
using AppDonnyCuevas20210074.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDonnyCuevas20210074.Migrations
{
    [DbContext(typeof(TurismoJimaniContext))]
    partial class TurismoJimaniContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Atractivo", b =>
                {
                    b.Property<int>("IdAtractivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtractivo"));

                    b.Property<bool>("Destacado")
                        .HasColumnType("bit");

                    b.Property<int?>("DuracionVisitaMinutos")
                        .HasColumnType("int");

                    b.Property<string>("EstadoConservacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLugar")
                        .HasColumnType("int");

                    b.Property<string>("InformacionAcceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacionCultural")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacionNatural")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelDificultad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoAtractivo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdAtractivo");

                    b.HasIndex("IdLugar")
                        .IsUnique();

                    b.ToTable("Atractivos");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.ConsultaAsistente", b =>
                {
                    b.Property<long>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdConsulta"));

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdSesion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IntencionDetectada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MensajeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaAsistente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RespuestaCorrecta")
                        .HasColumnType("bit");

                    b.Property<int?>("TiempoRespuestaMilisegundos")
                        .HasColumnType("int");

                    b.Property<string>("TipoRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdConsulta");

                    b.ToTable("ConsultasAsistente");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Contacto", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContacto"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<int>("IdLugar")
                        .HasColumnType("int");

                    b.Property<string>("TipoContacto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ValorContacto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdLugar");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.DatoCurioso", b =>
                {
                    b.Property<int>("IdDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDato"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fuente")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdDato");

                    b.ToTable("DatosCuriosos");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.DocumentoConocimiento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdReferencia")
                        .HasColumnType("int");

                    b.Property<string>("TipoFuente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdDocumento");

                    b.ToTable("DocumentosConocimiento");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.EjemploIntencion", b =>
                {
                    b.Property<int>("IdEjemplo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEjemplo"));

                    b.Property<int>("IdIntencion")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdEjemplo");

                    b.HasIndex("IdIntencion");

                    b.ToTable("EjemplosIntencion");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Destacado")
                        .HasColumnType("bit");

                    b.Property<string>("EnlaceExterno")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdLugar")
                        .HasColumnType("int");

                    b.Property<string>("ImagenAutor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImagenFuenteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LugarTexto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Organizador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Publicado")
                        .HasColumnType("bit");

                    b.Property<string>("Resumen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdEvento");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("IdLugar");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<bool>("Cerrado")
                        .HasColumnType("bit");

                    b.Property<byte>("DiaSemana")
                        .HasColumnType("tinyint");

                    b.Property<TimeSpan?>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<int>("IdLugar")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdLugar");

                    b.ToTable("Horarios", t =>
                        {
                            t.HasCheckConstraint("CK_Horarios_DiaSemana", "DiaSemana BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Imagen", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<string>("Autor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuenteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdLugar")
                        .HasColumnType("int");

                    b.Property<int?>("IdPrestador")
                        .HasColumnType("int");

                    b.Property<string>("Licencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrdenVisualizacion")
                        .HasColumnType("int");

                    b.Property<string>("TextoAlternativo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdImagen");

                    b.HasIndex("IdLugar");

                    b.HasIndex("IdPrestador");

                    b.ToTable("Imagenes", t =>
                        {
                            t.HasCheckConstraint("CK_Imagenes_Propietario", "(IdLugar IS NOT NULL AND IdPrestador IS NULL) OR (IdLugar IS NULL AND IdPrestador IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Intencion", b =>
                {
                    b.Property<int>("IdIntencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIntencion"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIntencion");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Intenciones");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Lugar", b =>
                {
                    b.Property<int>("IdLugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLugar"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCorta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdLugar");

                    b.ToTable("Lugares");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Prestador", b =>
                {
                    b.Property<int>("IdPrestador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestador"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCorta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Destacado")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EnlaceExterno")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HorarioAtencion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IdTipoPrestador")
                        .HasColumnType("int");

                    b.Property<string>("InformacionPrecio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("PrecioDesde")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecioHasta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RedSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("RequiereReserva")
                        .HasColumnType("bit");

                    b.Property<bool>("ServicioDomicilio")
                        .HasColumnType("bit");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ZonaCobertura")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdPrestador");

                    b.HasIndex("IdTipoPrestador");

                    b.HasIndex("Nombre");

                    b.ToTable("Prestadores");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Ruta", b =>
                {
                    b.Property<int>("IdRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRuta"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DistanciaKilometros")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdLugarDestino")
                        .HasColumnType("int");

                    b.Property<int?>("IdLugarOrigen")
                        .HasColumnType("int");

                    b.Property<string>("Instrucciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelDificultad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoTransporte")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdRuta");

                    b.HasIndex("IdLugarDestino");

                    b.HasIndex("IdLugarOrigen");

                    b.ToTable("Rutas");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdServicio");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.TipoPrestador", b =>
                {
                    b.Property<int>("IdTipoPrestador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPrestador"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoPrestador");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposPrestador");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CategoriaLugar", b =>
                {
                    b.Property<int>("CategoriasIdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("LugaresIdLugar")
                        .HasColumnType("int");

                    b.HasKey("CategoriasIdCategoria", "LugaresIdLugar");

                    b.HasIndex("LugaresIdLugar");

                    b.ToTable("LugarCategoria", (string)null);
                });

            modelBuilder.Entity("LugarServicio", b =>
                {
                    b.Property<int>("LugaresIdLugar")
                        .HasColumnType("int");

                    b.Property<int>("ServiciosIdServicio")
                        .HasColumnType("int");

                    b.HasKey("LugaresIdLugar", "ServiciosIdServicio");

                    b.HasIndex("ServiciosIdServicio");

                    b.ToTable("LugarServicio", (string)null);
                });

            modelBuilder.Entity("PrestadorServicio", b =>
                {
                    b.Property<int>("PrestadoresIdPrestador")
                        .HasColumnType("int");

                    b.Property<int>("ServiciosIdServicio")
                        .HasColumnType("int");

                    b.HasKey("PrestadoresIdPrestador", "ServiciosIdServicio");

                    b.HasIndex("ServiciosIdServicio");

                    b.ToTable("PrestadorServicio", (string)null);
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Atractivo", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", "Lugar")
                        .WithOne("Atractivo")
                        .HasForeignKey("AppDonnyCuevas20210074.Models.Atractivo", "IdLugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Contacto", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", "Lugar")
                        .WithMany("Contactos")
                        .HasForeignKey("IdLugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.EjemploIntencion", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Intencion", "Intencion")
                        .WithMany("Ejemplos")
                        .HasForeignKey("IdIntencion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intencion");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Evento", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("IdLugar")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Horario", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", "Lugar")
                        .WithMany("Horarios")
                        .HasForeignKey("IdLugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Imagen", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", "Lugar")
                        .WithMany("Imagenes")
                        .HasForeignKey("IdLugar")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AppDonnyCuevas20210074.Models.Prestador", "Prestador")
                        .WithMany("Imagenes")
                        .HasForeignKey("IdPrestador")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lugar");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Prestador", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.TipoPrestador", "TipoPrestador")
                        .WithMany("Prestadores")
                        .HasForeignKey("IdTipoPrestador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoPrestador");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Ruta", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", "LugarDestino")
                        .WithMany()
                        .HasForeignKey("IdLugarDestino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", "LugarOrigen")
                        .WithMany()
                        .HasForeignKey("IdLugarOrigen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LugarDestino");

                    b.Navigation("LugarOrigen");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Usuario", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CategoriaLugar", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", null)
                        .WithMany()
                        .HasForeignKey("LugaresIdLugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LugarServicio", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Lugar", null)
                        .WithMany()
                        .HasForeignKey("LugaresIdLugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDonnyCuevas20210074.Models.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServiciosIdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrestadorServicio", b =>
                {
                    b.HasOne("AppDonnyCuevas20210074.Models.Prestador", null)
                        .WithMany()
                        .HasForeignKey("PrestadoresIdPrestador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDonnyCuevas20210074.Models.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServiciosIdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Intencion", b =>
                {
                    b.Navigation("Ejemplos");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Lugar", b =>
                {
                    b.Navigation("Atractivo");

                    b.Navigation("Contactos");

                    b.Navigation("Horarios");

                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Prestador", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AppDonnyCuevas20210074.Models.TipoPrestador", b =>
                {
                    b.Navigation("Prestadores");
                });
#pragma warning restore 612, 618
        }
    }
}
